// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"userapi/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {

	userapiHandler := NewUserapiHandler(serverCtx)
	// 中间件（全局性质的）
	server.Use(serverCtx.UserMiddleware.GlobalMiddleware)
	// 不需要Token校验的路由
	server.AddRoutes(
		// 中间件（局部性质的,只是作用域包含的这些路由）
		rest.WithMiddlewares(
			[]rest.Middleware{
				serverCtx.UserMiddleware.LoginAndRegister,
			},
			rest.Route{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: userapiHandler.Register,
			},
			rest.Route{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: userapiHandler.Login,
			},
		),
	)
	// 需要Token校验的路由
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/get/:id",
				Handler: userapiHandler.GetUser,
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
