// Code generated by goctl. DO NOT EDIT.
// Source: userscore.proto

package server

import (
	"context"

	"rpc-common/types/userscore"
	"userscore/internal/logic"
	"userscore/internal/svc"
)

type UserScoreServer struct {
	svcCtx *svc.ServiceContext
	userscore.UnimplementedUserScoreServer
}

func NewUserScoreServer(svcCtx *svc.ServiceContext) *UserScoreServer {
	return &UserScoreServer{
		svcCtx: svcCtx,
	}
}

func (s *UserScoreServer) SaveUserScore(ctx context.Context, in *userscore.UserScoreRequest) (*userscore.UserScoreResponse, error) {
	l := logic.NewSaveUserScoreLogic(ctx, s.svcCtx)
	return l.SaveUserScore(in)
}

func (s *UserScoreServer) SaveUserScoreCallback(ctx context.Context, in *userscore.UserScoreRequest) (*userscore.UserScoreResponse, error) {
	l := logic.NewSaveUserScoreCallbackLogic(ctx, s.svcCtx)
	return l.SaveUserScoreCallback(in)
}
